/// Colores de flores para autocompletado en inventario.
const List<String> kFlowerColors = [
  'Ébano',
  'Black Baccara',
  'Centro negro',
  'Kokarde',
  'Black Jack',
  'Schwarzwalder',
  'Baya madura',
  'Centro verde',
  'Botella',
  'Queen of Night',
  'Centro gris',
  'Terciopelo',
  'Borgoña',
  'Centro café',
  'Oscuro brillante',
  'Profundo',
  'Ciruela',
  'Marino',
  'Medio',
  'Hoja',
  'Oscuro',
  'Violeta',
  'Acero',
  'Oscuro (Ming)',
  'Variegado',
  'Bordeaux',
  'Intenso',
  'Loro',
  'Vino',
  'Denim',
  'Cereza',
  'Granate',
  'Plateado azulado',
  'Púrpura',
  'Manzana',
  'Malva',
  'Carmesí',
  'Lavanda',
  'Viejo',
  'Bl+Violeta',
  'Cobrizo',
  'Baby Blue',
  'Pálido',
  'Rosa+Morado',
  'Terracota',
  'Silver Dollar',
  'Gris plateado',
  'Magenta',
  'Frambuesa',
  'Bronce',
  'Antiguo',
  'Lila',
  'Verde-amarillo nube',
  'Verde plateado',
  'Blanco plateado',
  'Menta',
  'Clásico',
  'Quemado',
  'Naranja',
  'Lila rosado',
  'Miel',
  'Cobre',
  'Ocre',
  'Fucsia',
  'Rosado lila',
  'Perla',
  'Lino',
  'Mandarina',
  'Stargazer',
  'Beige dorado',
  'Fuerte',
  'Champagne',
  'Chicle',
  'Azulado',
  'Verdoso',
  'Beige',
  'Marfil',
  'Coral',
  'Coral salmón',
  'Coral pálido',
  'Suave',
  'Albaricoque',
  'Melocotón',
  'Sol',
  'Dorado',
  'Canario',
  'Mantequilla',
  'Claro',
  'Crema',
  'Bi.Amarillo',
  'Escarlata',
  'Fuego',
  'Ardiente',
  'Rosa',
  'Bebé',
  'Pastel',
  'Limón',
  'Durazno',
  'Nieve',
  'Bl+Rosa',
  'Bl+Rojo',
];
